spin_manifest_version = 2

[application]
name = "kite"
version = "0.1.0"
authors = ["Seungjin Kim <seungjin@duck.com>"]
description = ""

[variables]
s3_access_key = { required = true, secret = true }
s3_secret_key = { required = true, secret = true }
s3_provider = { required = true }
s3_bucket = { required = true }
s3_endpoint = { required = true }
s3_region = { required = true }
domain = { required = true }

[[trigger.http]]
route = "/..."
component = "web"

[component.web]
source = "/wasm32-wasi/web.wasm"
sqlite_databases = ["default"]
key_value_stores = ["mem"]
allowed_outbound_hosts = ["https://*:*", "http://*:*"]

[[trigger.http]]
route = "/assets/..."
component = "static"

[[trigger.http]]
route = "/robots.txt"
component = "static"

[component.static]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.3.0/spin_static_fs.wasm", digest = "sha256:ef88708817e107bf49985c7cefe4dd1f199bf26f6727819183d5c996baa3d148" }
files = [{ source = "assets", destination = "/" }]

[[trigger.http]]
route = "/.well-known/..."
component = "well-known"

[component.well-known]
source = "/wasm32-wasi/well_known.wasm"
sqlite_databases = ["default"]
allowed_outbound_hosts = []

[[trigger.http]]
route = "/api/..."
component = "api"

[component.api]
source = "/wasm32-wasi/api.wasm"
allowed_outbound_hosts = [
    "https://*:*",
    "redis://{{ redis_host }}:{{ redis_port }}",
    "rediss://{{ redis_host }}:{{ redis_port }}",
]
sqlite_databases = ["default"]
key_value_stores = ["mem"]
[component.api.variables]
s3_access_key = "{{ s3_access_key }}"
s3_secret_key = "{{ s3_secret_key }}"
s3_provider = "{{ s3_provider }}"
s3_bucket = "{{ s3_bucket }}"
s3_endpoint = "{{ s3_endpoint }}"
s3_region = "{{ s3_region }}"
domain = "{{ domain }}"


[[trigger.http]]
route = "/oauth/..."
component = "oauth"

[component.oauth]
source = "/wasm32-wasi/oauth.wasm"
allowed_outbound_hosts = ["https://*:*"]
sqlite_databases = ["default"]
key_value_stores = ["mem"]
[component.oauth.variables]
domain = "{{ domain }}"

[[trigger.http]]
route = "/inbox/..."
component = "inbox"

[component.inbox]
source = "/wasm32-wasi/inbox.wasm"
sqlite_databases = ["default"]
key_value_stores = ["mem"]
allowed_outbound_hosts = ["https://*:*", "http://*:*"]

[[trigger.http]]
route = "/following/..."
component = "following"

[component.following]
source = "/wasm32-wasi/following.wasm"
sqlite_databases = ["default"]
key_value_stores = ["mem"]
allowed_outbound_hosts = ["https://*:*", "http://*:*"]

[[trigger.http]]
route = "/followers/..."
component = "followers"

[component.followers]
source = "/wasm32-wasi/followers.wasm"
sqlite_databases = ["default"]
key_value_stores = ["mem"]
allowed_outbound_hosts = ["https://*:*", "http://*:*"]

[[trigger.http]]
route = "/outbox/..."
component = "outbox"

[component.outbox]
source = "/wasm32-wasi/outbox.wasm"
sqlite_databases = ["default"]
key_value_stores = ["mem"]
allowed_outbound_hosts = []
