CREATE TABLE account (
    uid TEXT NOT NULL,
    username TEXT DEFAULT "" NOT NULL,
    domain TEXT,
    private_key TEXT,
    public_key TEXT DEFAULT "" NOT NULL,
    created_at TIMESTAMP DEFAULT (unixepoch()) NOT NULL,
    updated_at INTEGER DEFAULT (unixepoch()) NOT NULL,
    note TEXT DEFAULT "" NOT NULL,
    display_name TEXT DEFAULT "" NOT NULL,
    uri TEXT DEFAULT "" NOT NULL,
    url TEXT,
    avatar_file_name TEXT,
    avatar_content_type TEXT,
    avatar_file_size INTEGER,
    avatar_updated_at INTEGER,
    header_file_name TEXT,
    header_content_type TEXT,
    header_file_size INTEGER,
    header_updated_at INTEGER,
    avatar_remote_url TEXT,
    locked BOOLEAN DEFAULT FALSE NOT NULL,
    header_remote_url TEXT,
    last_webfingered_at INTEGER,
    inbox_url TEXT DEFAULT "" NOT NULL,
    outbox_url TEXT DEFAULT "" NOT NULL,
    shared_inbox_url TEXT DEFAULT "" NOT NULL,
    followers_url TEXT DEFAULT "" NOT NULL,
    following_url TEXT DEFAULT "" NOT NULL,
    protocol INTEGER DEFAULT 0 NOT NULL,
    memorial BOOLEAN DEFAULT FALSE NOT NULL,
    moved_to_account_id bigint,
    featured_collection_url TEXT,
    fields jsonb,
    actor_type TEXT,
    discoverable BOOLEAN,
    also_known_as TEXT,
    silenced_at INTEGER,
    suspended_at INTEGER,
    hide_collections BOOLEAN,
    avatar_storage_schema_version INTEGER,
    header_storage_schema_version INTEGER,
    devices_url TEXT,
    suspension_origin INTEGER,
    sensitized_at INTEGER,
    trendable BOOLEAN,
    reviewed_at INTEGER,
    requested_review_at INTEGER,
    indexable BOOLEAN DEFAULT FALSE NOT NULL
    --UNIQUE(username, domain)
);



