-- Add migration script here
CREATE TABLE user (
    uuid TEXT NOT NULL,
    email TEXT DEFAULT "" NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    encrypted_password TEXT DEFAULT "" NOT NULL,
    reset_password_token TEXT,
    reset_password_sent_at INTEGER,
    sign_in_count INTEGER DEFAULT 0 NOT NULL,
    current_sign_in_at INTEGER,
    last_sign_in_at INTEGER,
    admin BOOLEAN DEFAULT FALSE NOT NULL,
    confirmation_token TEXT,
    confirmed_at INTEGER,
    confirmation_sent_at INTEGER,
    unconfirmed_email TEXT,
    locale TEXT,
    encrypted_otp_secret TEXT,
    encrypted_otp_secret_iv TEXT,
    encrypted_otp_secret_salt TEXT,
    consumed_timestep INTEGER,
    otp_required_for_login BOOLEAN DEFAULT FALSE NOT NULL,
    last_emailed_at INTEGER,
    otp_backup_codes TEXT,
    account_id TEXT NOT NULL,
    disabled BOOLEAN DEFAULT FALSE NOT NULL,
    moderator BOOLEAN DEFAULT FALSE NOT NULL,
    invite_id INTEGER,
    chosen_languages TEXT,
    created_by_application_id INTEGER,
    approved BOOLEAN DEFAULT true NOT NULL,
    sign_in_token TEXT,
    sign_in_token_sent_at INTEGER,
    webauthn_id TEXT,
    sign_up_ip TEXT,
    skip_sign_in_token BOOLEAN,
    role_id INTEGER,
    settings TEXT,
    time_zone TEXT
);

/*


CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying DEFAULT ''::character varying NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    encrypted_password character varying DEFAULT ''::character varying NOT NULL,
    reset_password_token character varying,
    reset_password_sent_at timestamp without time zone,
    sign_in_count integer DEFAULT 0 NOT NULL,
    current_sign_in_at timestamp without time zone,
    last_sign_in_at timestamp without time zone,
    admin boolean DEFAULT false NOT NULL,
    confirmation_token character varying,
    confirmed_at timestamp without time zone,
    confirmation_sent_at timestamp without time zone,
    unconfirmed_email character varying,
    locale character varying,
    encrypted_otp_secret character varying,
    encrypted_otp_secret_iv character varying,
    encrypted_otp_secret_salt character varying,
    consumed_timestep integer,
    otp_required_for_login boolean DEFAULT false NOT NULL,
    last_emailed_at timestamp without time zone,
    otp_backup_codes character varying[],
    account_id bigint NOT NULL,
    disabled boolean DEFAULT false NOT NULL,
    moderator boolean DEFAULT false NOT NULL,
    invite_id bigint,
    chosen_languages character varying[],
    created_by_application_id bigint,
    approved boolean DEFAULT true NOT NULL,
    sign_in_token character varying,
    sign_in_token_sent_at timestamp without time zone,
    webauthn_id character varying,
    sign_up_ip inet,
    skip_sign_in_token boolean,
    role_id bigint,
    settings text,
    time_zone character varying
);

*/