CREATE TABLE media_attachments (
    uid TEXT NOT NULL,
    status_id TEXT,
    file_file_name TEXT,
    file_content_type TEXT,
    file_file_size i64,
    file_updated_at TIMESTAMP,
    remote_url TEXT DEFAULT '' NOT NULL,
    created_at TIMESTAMP DEFAULT (unixepoch()) NOT NULL,
    updated_at TIMESTAMP DEFAULT (unixepoch()) NOT NULL,
    shortcode TEXT,
    type INTEGER DEFAULT 0 NOT NULL,
    file_meta TEXT,
    account_id TEXT,
    description TEXT,
    scheduled_status_id TEXT,
    blurhash TEXT,
    processing INTEGER,
    file_storage_schema_version INTEGER,
    thumbnail_file_name TEXT,
    thumbnail_content_type TEXT,
    thumbnail_file_size INTEGER,
    thumbnail_updated_at TIMESTAMP,
    thumbnail_remote_url TEXT
);
