# [Choice] Debian OS version (use bookworm, or bullseye on local arm64/Apple Silicon): bookworm, buster, bullseye

ARG OS_VER="bookworm"
FROM rust:${OS_VER}

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    # Remove imagemagick due to https://security-tracker.debian.org/tracker/CVE-2019-10131
    && apt-get purge -y imagemagick imagemagick-6-common

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
     && apt-get -y install --no-install-recommends $(cat packages.debian | grep "^[^#;]")

ARG RACKET_VER=8.13
ARG RACKET_INSTALLER="racket-minimal-${RACKET_VER}-x86_64-linux-cs.sh"
ARG RACKET_INSTALLER_CHECKSUM="f73a5a1f4c3d5ef77f401d1e2e3f3294ad7d9075ff6fe8a16489c1eee91cd81c"

RUN wget https://download.racket-lang.org/releases/${RACKET_VER}/installers/${RACKET_INSTALLER}
#RUN if echo "f73a5a1f4c3d5ef77f401d1e2e3f3294ad7d9075ff6fe8a16489c1eee91cd81c racket-minimal-8.13-x86_64-linux-cs.sh" | sha256sum --check --status || [ $? -eq 0  ]; then /usr/bin/bash racket-minimal-8.13-x86_64-linux-cs.sh --unix-style --create-dir --dest /usr/local ; fi

RUN if echo "$RACKET_INSTALLER_CHECKSUM $RACKET_INSTALLER" | sha256sum --check --status || [ $? -eq 0  ]; then /usr/bin/bash $RACKET_INSTALLER --unix-style --create-dir --dest /usr/local ; fi

RUN rm -fr ${RACKET_INSTALLER}

RUN raco pkg install --auto racket-langserver





