name: Stage Release
on:
  push:
    branches: [u/seungjin/st]

jobs:
  assets:
    name: Build and release assets
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - name: set the release version (tag)
        run: echo "BUILD_VERSION=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV

      - name: Install latest Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          components: clippy, rustfmt

      - name: Install Wasm Rust target
        run: rustup target add wasm32-wasi

      - name: Make
        run: make build-wasm
        env:
          APP_LOG_LEVEL: TRACE

      - name: generate checksums
        run: |
          echo "API_CHECKSUM=$(sha256sum target/wasm32-wasi/release/api.wasm | awk '{print $1}')" >> $GITHUB_ENV
          echo "FOLLOWERS_CHECKSUM=$(sha256sum target/wasm32-wasi/release/followers.wasm | awk '{print $1}')" >> $GITHUB_ENV
          echo "FOLLOWING_CHECKSUM=$(sha256sum target/wasm32-wasi/release/following.wasm | awk '{print $1}')" >> $GITHUB_ENV
          echo "INBOX_CHECKSUM=$(sha256sum target/wasm32-wasi/release/inbox.wasm | awk '{print $1}')" >> $GITHUB_ENV
          echo "OAUTH_CHECKSUM=$(sha256sum target/wasm32-wasi/release/oauth.wasm | awk '{print $1}')" >> $GITHUB_ENV
          echo "OUTBOX_CHECKSUM=$(sha256sum target/wasm32-wasi/release/outbox.wasm | awk '{print $1}')" >> $GITHUB_ENV
          echo "WEB_CHECKSUM=$(sha256sum target/wasm32-wasi/release/web.wasm | awk '{print $1}')" >> $GITHUB_ENV
          echo "WELLKNOWN_CHECKSUM=$(sha256sum target/wasm32-wasi/release/well_known.wasm | awk '{print $1}')" >> $GITHUB_ENV

      - name: Render Checksum Template
        uses: recih/template-render-action@v1.0.2
        with:
          template-file: "checksums.template"
          engine: mustache
          output-file: checksums-${{ env.BUILD_VERSION }}.txt
          glob: false

      - name: Render Spin Template
        uses: recih/template-render-action@v1.0.2
        with:
          template-file: "spin.toml.template"
          engine: mustache
          output-file: spin.toml
          glob: false
          vars: |
            { "RUN_NUMBER": "${{ github.run_number }}" "}
            { "API": "${{ env.API_CHECKSUM }}" }
            { "FOLLOWERS": "${{ env.FOLLOWERS_CHECKSUM }}" }
            { "FOLLOWING": "${{ env.FOLLOWING_CHECKSUM }}" }
            { "INBOX": "${{ env.INBOX_CHECKSUM }}" }
            { "OAUTH": "${{ env.OAUTH_CHECKSUM }}" }
            { "OUTBOX": "${{ env.OUTBOX_CHECKSUM }}" }
            { "WEB": "${{ env.WEB_CHECKSUM }}" }
            { "WELLKNOWN": "${{ env.WELLKNOWN_CHECKSUM }}" }

      - name: Create release
        uses: softprops/action-gh-release@v2.0.8
        with:
          fail_on_unmatched_files: true
          generate_release_notes: true
          tag_name: stg-seungjin-${{ github.run_number }}
          make_latest: true
          files: |
            target/wasm32-wasi/release/api.wasm
            target/wasm32-wasi/release/followers.wasm
            target/wasm32-wasi/release/following.wasm
            target/wasm32-wasi/release/inbox.wasm
            target/wasm32-wasi/release/oauth.wasm
            target/wasm32-wasi/release/outbox.wasm
            target/wasm32-wasi/release/web.wasm
            target/wasm32-wasi/release/well_known.wasm
            checksums-${{ env.BUILD_VERSION }}.txt
            runtime-config.toml
            spin.toml
            compose.yaml
